### ISSUE TITLE
Not working on Windows11

### ISSUE THREAD

**Issue by saumyajyoti** [KKV9/archive.yazi#2]
I see no action when triggering the hotkey.

**Comment by KKV9** [comment]
If you are on the latest git version of yazi try the following steps:
https://github.com/KKV9/archive.yazi/issues/3#issuecomment-2227525407

Otherwise please provide the following:
Operating system, yazi version, install method and error message if any.

**Comment by saumyajyoti** [comment]
Thanks @KKV9 , it worked now. Earlier I used ya pack and it was installed as archive. Now I installed as compress.yazi via git clone method.
