### ISSUE TITLE
On Debian, compressing to `7z` fails because `7z` binary is actually named `7zz`

### ISSUE THREAD

**Issue by xfzv** [KKV9/archive.yazi#7]
On Debian 12, `7zip` package installs binary to `/usr/bin/7zz` ([source](https://packages.debian.org/bookworm/amd64/7zip/filelist)).

As a result, compressing to `7z` will fail:

https://github.com/KKV9/compress.yazi/blob/878b876b2ff0d48741eb3a4c4c2f149e962af43c/init.lua#L90

Note that `yazi` upstream repo has some `7zz` references:

https://github.com/search?q=repo%3Asxyazi%2Fyazi%207zz&type=code

**Comment by KKV9** [comment]
Hi, thanks for this. I added some logic to handle cases like this. If it works on your machine please let me know :)
